FORMAT: 1A

HOST: https://das-muc-staging-v2.jelastic.dogado.eu:4848

# IMP North. Implemented V2
This IMP API version 2.
Host V2: https://das-muc-staging-v2.jelastic.dogado.eu:4848
Host V1: https://das-muc-staging-imp.jelastic.dogado.eu:4848
cml host: http://cml-staging.jelastic.dogado.eu only IMR is working

# Readme before making any changes   

Please keep the groovy generating script in synch with this documentation. Read more on Wiki: https://confluence.imp.mobilitaetsdienste.de/display/IMP/Apiary. 

*update the goovy script if you change names of any chapter* 
*chapter names can not contain special characters "(", ")", "\", etc. which have a meaning in regular expressions*

# Introduction

This is a description of a public REST interface offered by Siemens AG VERSION 2 and its subsidiary VMZ Berlin Betreibergesellschaft GmbH 
in the project Open Mobility Berlin. A mockup of this interface can be tried using the URLs listed on the right. For access to the production
system please write an email to `henrik.koberg@siemens.com`

(c) Siemens AG 2014 All rights reserved


# Group Journey Planner. IMR
This is a group of all IMR journey planner related rest resources.

## List of Trip Proposals with Basic Info. Intermodal Router [/imp-endpoint/api/V2/TripProposals/IMR] 

This collection contains a list of trip proposals with basic information for specified trip criteria. Note: the trip proposals can be multimodal or intermodal, depending on which routing service the user is subscribed to.

The data structure of collection contains a list of trip proposals. Each trip proposal contains the following attributes:

attribute | json data type | comments
--- | --- | ---
url | URI | URI to request more details
origin | Object | start point of the proposed trip
destination | Object | endpoint of the proposed trip
trafficTypes | Array | list of traffic types used in the proposed trip. Possible values: Bike, Bus, Car, CityTrain, Ferry, Metro, Other, RegioTrain, Unknown, Train, Tram, Walk, UBahn. trafficType Other is used in the segments for car rental/parking
description | String | description of the trip proposal
costs | Array | list of costs for the proposed trip including distance, duration, price, etc.

    
+ Model (application/json)

    + Body
    
            {
                "metaData": [
                    {
                        "serviceAlias": "vmzImrRouting",
                        "lastUpdateTime": "2014-12-16T12:26:29+00:00",
                        "messages": []
                    }
                ],
                "tripProposals": [
                    {
                        "url": "TripProposals/IMR/39",
                        "origin": {
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    13.4113422,
                                    52.5218455
                                ]
                            },
                            "address": "Dircksenstraße, 10178 Berlin, Germany",
                            "time": "2013-07-23T13:10:00+00:00"
                        },
                        "destination": {
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    13.3194514,
                                    52.5635387
                                ]
                            },
                            "address": "Meteorstraße 40, 13405 Berlin, Germany",
                            "time": "2013-07-23T15:17:54+00:00"
                        },
                        "trafficTypes": [
                            "OwnBike",
                            "Other",
                            "Walk"
                        ],
                        "description": null,
                        "costs": {
                            "distance": {
                                "unit": "Meter",
                                "value": 10264
                            },
                            "duration": {
                                "unit": "Minute",
                                "value": 127.9
                            },
                            "price": {
                                "unit": "Euro",
                                "value": 0.024444444444444442
                            },
                            "emission": {
                                "unit": "Gram",
                                "value": 0
                            },
                            "ticketPrice": null
                        }
                    },
                    {
                        "url": "TripProposals/IMR/40",
                        "origin": {
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    13.4113422,
                                    52.5218455
                                ]
                            },
                            "address": "Dircksenstraße, 10178 Berlin, Germany",
                            "time": "2013-07-23T13:10:00+00:00"
                        },
                        "destination": {
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    13.3194514,
                                    52.5635387
                                ]
                            },
                            "address": "Meteorstraße 40, 13405 Berlin, Germany",
                            "time": "2013-07-23T15:16:53+00:00"
                        },
                        "trafficTypes": [
                            "OwnBike",
                            "Other",
                            "Walk"
                        ],
                        "description": null,
                        "costs": {
                            "distance": {
                                "unit": "Meter",
                                "value": 10207
                            },
                            "duration": {
                                "unit": "Minute",
                                "value": 126.88333333333334
                            },
                            "price": {
                                "unit": "Euro",
                                "value": 0.025
                            },
                            "emission": {
                                "unit": "Gram",
                                "value": 0
                            },
                            "ticketPrice": null
                        }
                    }
            }


### Getting Trip Proposals by IMR Planner  [POST]
@testable

Selection criteria for trip proposals is specified in the request body as described in the sample request with the following attributes:

attribute | json data type | comments
--- | --- | ---
origin | Object | start point specified by a geo location (optionally can also include starttime). (addresses can be converted into geo locations by means of "GET /Resources/GeoLocations")
destination | Object | end point specified by a geo location (optional can also include endtime). Note if time in the origin is specified, time in the destination is discarded! If no time is specified current time is taken.
viapoints | Array of Objects | list of geolocations the route should pass
costfunctions | Array of Objects | list of cost factors, (such as Distance, Duration, Price, Emission), each with a percentual weight. Sample custfunction: {"costType":"Duration","percentage":"100"}
ownVehicles | Array of Objects | list of own vehicles which should be included into trip proposal calculation. Sample object value {"trafficType":"Car", "useParking":true,"useParkAndRide":false, "location":{"longitude":13.064472900000055,"latitude":52.3905689,"system":"WGS84"}}
userId | String | traveller id that requests a trip. Note: currently not used by IMP and can be any string
trafficTypes | Array | list of traffic types wich should be included into trip proposal calculation. Currently possible: Bike, Bus, Car, CityTrain, Ferry, Metro, Other, RegioTrain, Unknown, Train, Tram, Walk, UBahn. trafficType Other is used in the segments for car rental/parking
routingConstraints | Array of Objects | list of constraints to be taken into account for various traffic types, specified by min/max values. E.q. maximal distance in meters the traveller agrees to walk: {"routingConstraintType": "Distance", "trafficType": "Walk", "min": { "value": 0,"unit": "Meter" }, "max":{"value":600, "unit":"Meter"}}
useBikeSharing | Boolean | use bike sharing services for routing [default: false]
useCarSharing | Boolean | use car sharing services for routing [default: false]

Notes:
- IMR also provides routes in the past, but not for public transport
- route calculation the IMR takes into account information about current traffic situation (traffic jams/road works/...)
- Traveling time costs for proposed journeys include the following extra time: 2 minutes set-up time and 1 minute return time for free-floating car sharing and bike sharing; 2 minutes set-up time and 0 minutes return time for station-based car and bike sharing, 5 minutes parking time for free-floating car sharing and own car




+ Request

    + Headers
    
            Content-Type: application/json
            Accept: application/json

    + Body
        
            {
              "origin": {
                "location": {"type": "Point", "coordinates": [ 13.41100700000004, 52.521642 ]}
              },
              "destination": {
                "location": {"type": "Point", "coordinates": [ 13.319420000000036, 52.56347100000001 ]}
              },
              "time": "2013-07-23T15:10:00+02:00",
              "departureTime":"true",
              "costFunctions": [
                {
                  "costType": "Price",
                  "percentage": 100
                }
              ],
              "userId": "4711/10",
              "trafficTypes": ["Walk","Bike","Car","Metro","CityTrain","Bus"],
              "routingConstraints": [],
              "ownVehicles": [
                {
                    "trafficType": "Car",
                    "location": {"type": "Point", "coordinates": [ 13.41100700000004, 52.521642 ]},
                    "useParking": "false",
                    "useParkAndRide": "true",
                    "cost":{"price":{"price":{"value": 2, "currency":"EURO"},"distance":{"value":1, "unit":"KM"}}, "emission":{"mass":{"value": 2, "unit":"GRAM"},"distance":{"value":1, "unit":"KM"}}}
                },
                {
                    "trafficType": "Bike",
                    "location": {"type": "Point", "coordinates": [ 13.41100700000004, 52.521642 ]}
                } 
              ],
              "maxRoutingResponses": 4,
              "numOfTravelers" : 2,
              "numOfLuggage" : 2,
              "useTrafficSituation" : true
            }

+ Response 200

    [List of Trip Proposals with Basic Info. Intermodal Router][]


## Trip Proposal with Detailed Info [/imp-endpoint/api/V2/TripProposals/IMR/{proposalId}]

A single trip proposal object with Detailed Information. 
Each trip proposal consists of several segments, one segment for one transportation modality such as bike, car, train, etc. 
There is also a separate segment if the traveler shall use different lines of the same transport modality, 
for instance, first U5 from A to B and then U4 from B to C. Each segement has an origin and a destination with corresponding timestamps when to arrive and depart.
A segment consists of a sequence of wayPoints and guidingPoints.
A wayPoint describes an intermediate geo location useful for displaying the trip proposal in a map.
A guidingPoint gives a traveler hints how to travel, e.g., whenever to change the road at a crossing. GuidingPoints are a subset of wayPoints

The data structure of the trip proposal with detailed info contains the basic information attributes (*[POST /imp-endpoint/api/V2/TripProposals/IMR]*) and additionally the following attributes:

attribute | json data type | comments
--- | --- | ---
segmentId | URI | URI to request more details
origin | Object | start point of the proposed trip. For car sharing segment we have "operatorId" and "unitId" and for CityTrain/RegioTrain segment we have "platform", "stationId" and "direction"
destination | Object | endpoint of the proposed trip


Notes:
- The trip proposals as returned by *[GET /imp-endpoint/api/V2/TripProposals/IMR]* are internally stored only for a certain time; afterward they expire and details are no longer available. The current expiration time is 10 minutes.

### Getting a specific Trip Proposal [GET] 
@nottestable

+ Parameters
    + proposalId (string, `43`) ... String `proposalId` as retrieved through *[GET /imp-endpoint/api/V2/TripProposals/IMR]*

        
+ Response 200 (application/json)

            {
                "url": "TripProposals/IMR/43/",
                "segments": [
                    {
                        "segmentId": "1",
                        "description": null,
                        "origin": {
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    13.4113422,
                                    52.5218455
                                ]
                            },
                            "address": "Dircksenstraße, 10178 Berlin, Germany",
                            "time": "2013-07-23T13:10:00+00:00"
                        },
                        "destination": {
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    13.3194514,
                                    52.5635387
                                ]
                            },
                            "address": "Meteorstraße 40, 13405 Berlin, Germany",
                            "time": "2013-07-23T13:43:26+00:00"
                        },
                        "trafficType": "OwnBike",
                        "cost": {
                            "distance": {
                                "unit": "Meter",
                                "value": 8929
                            },
                            "duration": {
                                "unit": "Minute",
                                "value": 33.43333333333333
                            },
                            "price": {
                                "unit": "Euro",
                                "value": 0
                            },
                            "emission": {
                                "unit": "Gram",
                                "value": 0
                            },
                            "ticketPrice": null
                        },
                        "wayPoints": {
                            "type": "LineString",
                            "coordinates": [
                                [
                                    13.41134,
                                    52.52185
                                ],
                                [
                                    13.41018,
                                    52.52253
                                ],
                                [
                                    13.41007,
                                    52.52249
                                ],
                                [
                                    13.40999,
                                    52.52254
                                ],
                                [
                                    13.40983,
                                    52.52266
                                ],
                                [
                                    13.40973,
                                    52.52271
                                ],
                                [
                                    13.4097,
                                    52.52271
                                ],
                                [
                                    13.40957,
                                    52.52265
                                ],
                                [
                                    13.40884,
                                    52.52291
                                ]
                            ]
                        },
                        "guidingPoints": [
                            {
                                "description": "Head <b>northwest</b> on <b>Dircksenstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.4113422,
                                            52.5218455
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 0
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 0
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>left</b> toward <b>Dircksenstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.4101836,
                                            52.5225302
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 109
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 18
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Slight <b>left</b> at <b>Karl-Liebknecht-Straße/B2/B5</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.4098325,
                                            52.5226607
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 143
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 50
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>right</b> onto <b>Dircksenstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.4095731,
                                            52.5226482
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 165
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 79
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>right</b> onto <b>Rochstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.4071934,
                                            52.5234134
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 348
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 117
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Continue onto <b>Max-Beer-Straße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.407923,
                                            52.5245246
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 481
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 140
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>left</b> onto <b>Linienstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.409525,
                                            52.5282282
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 907
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 227
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>right</b> onto <b>Kleine Hamburger Str.</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.394919,
                                            52.528035
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 1923
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 389
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Continue onto <b>Gartenstraße</b><div style=\"font-size:0.9em\">Go through 1 roundabout</div>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3938246,
                                            52.5285362
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 2016
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 407
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Continue onto <b>Gerichtstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3781073,
                                            52.5418502
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 3889
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 887
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>left</b> to stay on <b>Gerichtstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3680708,
                                            52.5449003
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 4677
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1084
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>right</b> onto <b>Müllerstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3619344,
                                            52.5449205
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 5097
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1156
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Continue onto <b>Scharnweberstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3321398,
                                            52.5617735
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 7849
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1771
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>left</b> onto <b>Kurt-Schumacher-Damm</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3278148,
                                            52.5641527
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 8244
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1846
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>right</b> onto <b>Str. 462</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3268827,
                                            52.5632209
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 8365
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1911
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>left</b> onto <b>Nordlichtstraße</b>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3250669,
                                            52.5630978
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 8490
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1929
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Turn <b>right</b> onto <b>Meteorstraße</b><div style=\"font-size:0.9em\">Destination will be on the left</div>",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3248337,
                                            52.5625748
                                        ]
                                    },
                                    "address": null,
                                    "time": null
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 8550
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 1940
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            },
                            {
                                "description": "Meteorstraße 40, 13405 Berlin, Germany",
                                "location": {
                                    "location": {
                                        "type": "Point",
                                        "coordinates": [
                                            13.3194514,
                                            52.5635387
                                        ]
                                    },
                                    "address": "Meteorstraße 40, 13405 Berlin, Germany",
                                    "time": "2013-07-23T13:43:26+00:00"
                                },
                                "cost": {
                                    "distance": {
                                        "unit": "Meter",
                                        "value": 8929
                                    },
                                    "duration": {
                                        "unit": "Second",
                                        "value": 2006
                                    },
                                    "price": null,
                                    "emission": null,
                                    "ticketPrice": null
                                },
                                "operator": null,
                                "pointId": null,
                                "comment": []
                            }
                        ]
                    }
                ]
            }
